-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Acer Technologies Acer XR341CK T3MAA0014200",
  mode = "3440x1440@29.97",
  position = "-4998x-501",
  scale = 1,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG ULTRAFINE 508RMGCCD663",
  mode = "3840x2160@60.00",
  position = "-1558x0",
  scale = 1.5,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG ULTRAFINE 508RMMDCD643",
  mode = "3840x2160@60.00",
  position = "4442x0",
  scale = 1.5,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Sceptre Tech Inc Sceptre O34",
  mode = "3440x1440@180.00",
  position = "1002x0",
  scale = 1,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Sceptre Tech Inc Sceptre O34", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Sceptre Tech Inc Sceptre O34" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Sceptre Tech Inc Sceptre O34" })
hl.workspace_rule({ workspace = "4", monitor = "desc:LG Electronics LG ULTRAFINE 508RMMDCD643", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:LG Electronics LG ULTRAFINE 508RMMDCD643" })
hl.workspace_rule({ workspace = "6", monitor = "desc:LG Electronics LG ULTRAFINE 508RMMDCD643" })
hl.workspace_rule({ workspace = "7", monitor = "desc:LG Electronics LG ULTRAFINE 508RMGCCD663", default = true, persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "desc:LG Electronics LG ULTRAFINE 508RMGCCD663" })
hl.workspace_rule({ workspace = "9", monitor = "desc:LG Electronics LG ULTRAFINE 508RMGCCD663" })
